### ISSUE TITLE
Site doesn't load any project on home page

### ISSUE THREAD

**Issue by ytrkptl** [zero-to-mastery/Canvas-Creations#111]
Hey, why does the homepage not work anymore?
![Screenshot 2020-10-03 203439](https://user-images.githubusercontent.com/35569392/95004344-f7d4bb00-05b7-11eb-9c28-f3c1a272902a.png)

**Comment by michaeljoy255** [comment]
Made PR #112 to correct this issue.

**Comment by ytrkptl** [comment]
Yup it's fixed now.
