### ISSUE TITLE
trouble forking from invalid path

### ISSUE THREAD

**Issue by KevinToft** [zero-to-mastery/Canvas-Creations#205]
Hey all, I just forked the project and cloned it to my windows machine and I'm getting a error because of a colon used in a recently added file name.

error: invalid path 'Art/Angel_Lakra/randomize art.jpg:Zone.Identifier'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

Did a little digging and it turns out that ":" along with several other characters are not allowed while naming files in Windows.
Documentation-> https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

This will probably make it impossible for Windows users to successfully clone the repo..but then again this is my first contribution  to anything open source so I could be wrong. @joedag32

**Comment by kennithnichol** [comment]
That is a great observation @KevinToft .

From what I can see, the filename has been corrected. It looks like @sophiabrandt did a clean up on the repository shortly after the bug you noticed occurred.

I will close this issue, if you still have troubles please feel free to re-open it.
